config/routes.rb
Ooug::Application.routes.draw do
  root 'main_page#home'

  if Rails.env.production?
    get '/not_found', :to => 'errors#page_not_found'
  end

  match '/home', to: 'main_page#home', via: 'get'
  match '/help', to: 'main_page#help', via: 'get'
  match '/signUp', to: 'users#new', via: 'get'
  match '/about', to: 'main_page#about', via: 'get'
  match '/contact', to: 'main_page#contact', via: 'get'
  match '/inventory/test', to: 'inventory#test', via: 'get'
  match '/signIn',  to: 'sessions#new',         via: 'get'
  match '/signOut', to: 'sessions#destroy',     via: 'delete'

  get '/users/gruffBig' => 'users#gruffBig', as: 'gruffBig'
  get '/users/gruffSmall' => 'users#gruffSmall', as: 'gruffSmall'
  get '/users/gruffBigAcc' => 'users#gruffBigAcc', as: 'gruffBigAcc'
  get '/users/gruffSmallAcc' => 'users#gruffSmallAcc', as: 'gruffSmallAcc'
  get '/users/gruffConsole' => 'users#gruffConsole', as: 'gruffConsole'
  get '/users/gruffWish' => 'users#gruffWish', as: 'gruffWish'

  get '/wish_list/games/:id' => 'wish_list#games', as: 'wish_list_games'
  get '/wish_list/games/:id/:console_id' => 'wish_list#games', as: 'wish_list_game'

  get '/wish_list/accessories/:id' => 'wish_list#accessories', as: 'wish_list_accessories'
  get '/wish_list/accessories/:id/:console_id' => 'wish_list#accessories', as: 'wish_list_accessory'

  get '/wish_list/consoles/:id' => 'wish_list#consoles', as: 'wish_list_consoles'
  get '/wish_list/consoles/:id/:console_id' => 'wish_list#consoles', as: 'wish_list_console'
  
  get '/inventory/games/:id' => 'inventory#games', as: 'inventory_games'
  get '/inventory/games/:id/:console_id' => 'inventory#games', as: 'inventory_game'

  get '/inventory/consoles/:id' => 'inventory#consoles', as: 'inventory_consoles'
  get '/inventory/consoles/:id/:console_id' => 'inventory#consoles', as: 'inventory_console'

  get '/inventory/accessories/:id' => 'inventory#accessories', as: 'inventory_accessories'
  get '/inventory/accessories/:id/:console_id' => 'inventory#accessories', as: 'inventory_accessory'

  get '/ownership/new/:id' => 'ownership#new', as: 'new_ownership'
  get '/console_ownership/new/:id' => 'console_ownership#new', as: 'new_console_ownership'
  get '/accessories_ownership/new/:id' => 'accessories_ownership#new', as: 'new_accessories_ownership'

  get '/games_wish_list/new/:id' => 'games_wish_list#new', as: 'new_games_wish_list'
  get '/accessories_wish_list/new/:id' => 'accessories_wish_list#new', as: 'new_accessories_wish_list'  
  get '/consoles_wish_list/new/:id' => 'consoles_wish_list#new', as: 'new_consoles_wish_list'  

  resources :inventory, only: [:games, :consoles, :accessories]
  resources :users
  resources :games
  resources :wish_list
  resources :games_wish_list
  resources :accessories_wish_list
  resources :consoles_wish_list
  resources :browse_consoles
  resources :browse_accessories
  resources :consoles
  resources :accessories
  resources :console_general
  resources :console_ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :accessories_ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :region
  resources :ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :browse
  resources :search, only: [:index]
  resources :add_game, only: [:new, :create]
  resources :stats, only: [:show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :application, only: [:page_not_found]

  if Rails.env.production?
    get '*path' => redirect('/not_found')
  end
end

app/models/wish_list.rb
class WishList <ActiveRecord::Base
self.pluralize_table_names = false

end

app/controllers/wish_list_controller.rb
class WishListController < ApplicationController
	before_action :signed_in_user

	before_action :correct_user,   only: [:edit, :update, :show, :destroy, :edit]

	def games
		@remember_token = User.hash_token(cookies[:remember_token])
		@user = User.find_by(remember_token: @remember_token)

		@wish_list = GamesWishList.find_by(user_id: current_user())
		@game = GamesWishList.joins(:user).where(:users => {:id => current_user()})

		@gameConsoles = GamesWishList.where(user_id: @user).joins(:games => :console_general).order("eng_name").uniq.pluck(:eng_name)

		if (params.has_key?(:console_id))
			@game = GamesWishList.where(user_id: current_user().id).joins(:games => :console_general).where(:console_general => {:eng_name => params[:console_id]})

		else
			@game = GamesWishList.joins(:user).where(:users => {:id => current_user()})

		end

		@image = Image.all

	end

	def accessories
		@remember_token = User.hash_token(cookies[:remember_token])
		@user = User.find_by(remember_token: @remember_token)

		@wish_list = AccessoriesWishList.find_by(user_id: current_user())
		@game = AccessoriesWishList.joins(:user).where(:users => {:id => current_user()})

		@gameConsoles = AccessoriesWishList.where(user_id: @user).joins(:accessories => :console_general).order("eng_name").uniq.pluck(:eng_name)

		if (params.has_key?(:console_id))
			@game = AccessoriesWishList.where(user_id: current_user().id).joins(:accessories => :console_general).where(:console_general => {:eng_name => params[:console_id]})

		else
			@game = AccessoriesWishList.joins(:user).where(:users => {:id => current_user()})

		end

		@image = Image.all
	end

	def consoles
		@remember_token = User.hash_token(cookies[:remember_token])
		@user = User.find_by(remember_token: @remember_token)

		@wish_list = ConsolesWishList.find_by(user_id: current_user())
		@game = ConsolesWishList.joins(:user).where(:users => {:id => current_user()})

		@gameConsoles = ConsolesWishList.where(user_id: @user).joins(:consoles => :console_general).order("console_general.eng_name").uniq.pluck("console_general.eng_name")

		if (params.has_key?(:console_id))
			@game = ConsolesWishList.where(user_id: current_user().id).joins(:consoles => :console_general).where(:console_general => {:eng_name => params[:console_id]})

		else
			@game = ConsolesWishList.joins(:user).where(:users => {:id => current_user()})

		end

		@image = Image.all
	end

	private
	def wish_list_params
		params.require(:games_wish_list).permit(@user.id, :games_id, :notes)
	end

	def delete_params
		params.require(:ownership).permit(:id, :ean, :eng_title, :jap_title, :system, :region, :image)
	end

 # Before filters
 def signed_in_user
 	unless signed_in?
 		store_location
 		redirect_to signIn_url, notice: "Please sign in."
 	end
 end

 def correct_user
 	@user = User.find(GamesWishList.find(params[:id]).user_id)
 	redirect_to current_user, notice: "Sorry, you can't edit someone else's wish list"  unless current_user?(@user)
 end 
 
end

app/helpers/wish_list_helper.rb
module WishListHelper
end

app/views/wish_list/accessories.html.erb
<%= render 'layouts/accessoriesWishListSideBar' %>

<div class="container inventory-games" style="position: static">
    <% 
        if (params.has_key?(:console_id))
            provide(:title, 'All your wished for ' + params[:console_id] + ' accessories') 
        else
            provide(:title, 'Your Accessories Wish List') 
        end
    %>

    <table class="games-table">
        <% @game.each do |game| %>
            <tr>
                <td></td>
                <td class="game-title" id="game_info">
                    <%= link_to truncate(game.accessories.eng_title), accessories_wish_list_path(game.id) %>
                </td>
                <td class="game-console" id="console_info">
                    <%= link_to truncate(game.accessories.console_general.eng_name, :length => 22), console_general_path(game.accessories.console_general.id) %>
                </td>
                <td class="game-region" id="region_info">
                    <%= link_to game.accessories.region.region_title, region_path(game.accessories.region.region_id) %>
                </td>
            </tr>
        <% end %>
    </table>
</div>

app/views/wish_list/consoles.html.erb
<%= render 'layouts/consolesWishListSideBar' %>
<div class="container inventory-games" style="position: static">
    <%
        if (params.has_key?(:console_id))
            provide(:title, 'All your wished for ' + params[:console_id] + ' consoles') 
        else
            provide(:title, 'Your consoles Wish List') 
        end
    %>
    <table class="games-table">
        <% @game.each do |game| %>
            <tr>
                <td></td>
                <td class="game-title" id="game_info">
                    <%= link_to truncate(game.consoles.eng_name), consoles_wish_list_path(game.id) %>
                </td>
                <td class="game-console" id="console_info">
                    <%= link_to truncate(game.consoles.console_general.eng_name, :length => 22), console_general_path(game.consoles.console_general.id) %>
                </td>
                <td class="game-region" id="region_info">
                    <%= link_to game.consoles.region.region_title, region_path(game.consoles.region.region_id) %>
                </td>
            </tr>
        <% end %>
    </table>
</div>

app/views/wish_list/games.html.erb
<%= render 'layouts/gamesWishListSideBar' %>
<div class="container inventory-games" style="position: static">
    <% 
        if (params.has_key?(:console_id))
            provide(:title, 'All your wished for ' + params[:console_id] + ' games') 
        else
            provide(:title, 'Your Wish List') 
        end
    %>

    <table class="games-table">
        <% @game.each do |game| %>
            <tr height="50px">
                <td></td>
                <td class="game-title" id="game_info">
                    <%= link_to truncate(game.games.eng_title), games_wish_list_path(game.id) %>
                </td>
                <td class="game-console" id="console_info">
                    <%= link_to truncate(game.games.console_general.eng_name, :length => 22), console_general_path(game.games.console_general.id) %>
                </td>
                <td class="game-region" id="region_info">
                    <%= link_to game.games.region.region_title, region_path(game.games.region.region_id) %>
                </td>
            </tr>
        <% end %>

    </table>
</div>