config/routes.rb
Ooug::Application.routes.draw do
  root 'main_page#home'

  if Rails.env.production?
    get '/not_found', :to => 'errors#page_not_found'
  end

  match '/home', to: 'main_page#home', via: 'get'
  match '/help', to: 'main_page#help', via: 'get'
  match '/signUp', to: 'users#new', via: 'get'
  match '/about', to: 'main_page#about', via: 'get'
  match '/contact', to: 'main_page#contact', via: 'get'
  match '/inventory/test', to: 'inventory#test', via: 'get'
  match '/signIn',  to: 'sessions#new',         via: 'get'
  match '/signOut', to: 'sessions#destroy',     via: 'delete'

  get '/users/gruffBig' => 'users#gruffBig', as: 'gruffBig'
  get '/users/gruffSmall' => 'users#gruffSmall', as: 'gruffSmall'
  get '/users/gruffBigAcc' => 'users#gruffBigAcc', as: 'gruffBigAcc'
  get '/users/gruffSmallAcc' => 'users#gruffSmallAcc', as: 'gruffSmallAcc'
  get '/users/gruffConsole' => 'users#gruffConsole', as: 'gruffConsole'
  get '/users/gruffWish' => 'users#gruffWish', as: 'gruffWish'

  get '/wish_list/games/:id' => 'wish_list#games', as: 'wish_list_games'
  get '/wish_list/games/:id/:console_id' => 'wish_list#games', as: 'wish_list_game'

  get '/wish_list/accessories/:id' => 'wish_list#accessories', as: 'wish_list_accessories'
  get '/wish_list/accessories/:id/:console_id' => 'wish_list#accessories', as: 'wish_list_accessory'

  get '/wish_list/consoles/:id' => 'wish_list#consoles', as: 'wish_list_consoles'
  get '/wish_list/consoles/:id/:console_id' => 'wish_list#consoles', as: 'wish_list_console'
  
  get '/inventory/games/:id' => 'inventory#games', as: 'inventory_games'
  get '/inventory/games/:id/:console_id' => 'inventory#games', as: 'inventory_game'

  get '/inventory/consoles/:id' => 'inventory#consoles', as: 'inventory_consoles'
  get '/inventory/consoles/:id/:console_id' => 'inventory#consoles', as: 'inventory_console'

  get '/inventory/accessories/:id' => 'inventory#accessories', as: 'inventory_accessories'
  get '/inventory/accessories/:id/:console_id' => 'inventory#accessories', as: 'inventory_accessory'

  get '/ownership/new/:id' => 'ownership#new', as: 'new_ownership'
  get '/console_ownership/new/:id' => 'console_ownership#new', as: 'new_console_ownership'
  get '/accessories_ownership/new/:id' => 'accessories_ownership#new', as: 'new_accessories_ownership'

  get '/games_wish_list/new/:id' => 'games_wish_list#new', as: 'new_games_wish_list'
  get '/accessories_wish_list/new/:id' => 'accessories_wish_list#new', as: 'new_accessories_wish_list'  
  get '/consoles_wish_list/new/:id' => 'consoles_wish_list#new', as: 'new_consoles_wish_list'  

  resources :inventory, only: [:games, :consoles, :accessories]
  resources :users
  resources :games
  resources :wish_list
  resources :games_wish_list
  resources :accessories_wish_list
  resources :consoles_wish_list
  resources :browse_consoles
  resources :browse_accessories
  resources :consoles
  resources :accessories
  resources :console_general
  resources :console_ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :accessories_ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :region
  resources :ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :browse
  resources :search, only: [:index]
  resources :add_game, only: [:new, :create]
  resources :stats, only: [:show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :application, only: [:page_not_found]

  if Rails.env.production?
    get '*path' => redirect('/not_found')
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	before_action :empty_search, only: [:index]

	def index
		@search = params[:search]
		wildcard_search = "%#{@search}%"

		@results1 = Games.where("eng_title like :search or ean like :search", search: wildcard_search).all
		@results2 = Accessories.where("eng_title like :search or accessories_ean like :search", search: wildcard_search).all
		@results3 = Consoles.where("eng_name like :search or console_ean like :search", search: wildcard_search).all

		@count1 = @results1.count
		@count2 = @results2.count
		@count3 = @results3.count
	end

	private

	def empty_search
		if params[:search] == ''
			session[:return_to] ||= request.referer
			redirect_to session.delete(:return_to), notice: "Please enter a search query"
		end
	end
end

app/helpers/search_helper.rb
module SearchHelper

  def search_string(string)
    @search_string = string
  end

  def in_collection(game)
    @inCollection = Ownership.find_by(user_id: current_user().id, games_id: game.id)
  end

  def in_acc_collection(accessory)
    @inCollection = AccessoriesOwnership.find_by(user_id: current_user().id, accessories_id: accessory.id)
  end

  def in_console_collection(console)
    @inCollection = ConsoleOwnership.find_by(user_id: current_user().id, consoles_id: console.id)
  end


end

app/views/search/index.html.erb
<% provide(:title, @search) %>
<div class="tab-content">

	<% if signed_in? %>
	<%= link_to "Can't find a game?", new_game_path, class: "pull-right" %>
	<% end %>

	<ul class="nav nav-tabs" id="game_count_tabs">
		<li class="active"><a href="#game-search-results" data-toggle="tab">Games</a></li>
		<li><a href="#accessory-search-results" data-toggle="tab">Accessories</a></li>
		<li><a href="#console-search-results" data-toggle="tab">Consoles</a></li>
	</ul>

	<div class="tab-content">

		<div class="tab-pane active" id="game-search-results">
			<div class="row">
				<div class="span7 offset2">

					<% @num = 0 %>
					<% if !@results1.blank? %>

					<table class="search_results">
						<% @results1.each do |result| %>
						<% @num+=1 %>
						<% if @num % 10 == 0 %>
						<div class="tab-pane" id="<%=@num/10%>">
							<% end %>
							<tr>

								<td id="game_info">
									<% if signed_in? %>
									<% if in_collection(result) %>
									<span class="icon-ok-sign" title="You Own This"></span>  
									<% end %>
									<% end %>


									<%= link_to result.eng_title,  result%>
								</td>

								<td id="console_info">
									<%= result.console_general.eng_name %>
								</td>

								<td id="region_info">
									<%= link_to result.region.region_title, region_path(result.region.region_id) %>
								</td>

							</tr>
							<% if @num + 2 % 10 == 0%>
						</div>
						<% end %>
						<% end %>
					</table>

					<% else %>
					<h6>Sorry, we couldn't find anything</h6>

					<%= form_tag search_index_path, class: "navbar-form navbar-left", style: "text-align: center", method: "get" do %>
					<div class="input-prepend">
						<span class="icon-search"></span>  
						<%= text_field_tag :search, params[:search],  class: "span2 search-query", placeholder: "Search for a game"%>
					</div>
					<% end %>
					<% end %>
				</div>
			</div>

		</div>

		<div class="tab-pane fade in" id="accessory-search-results">
			<div class="row">
				<div class="span7 offset2">

					<% @num = 0 %>
					<% if !@results2.blank? %>

					<table class="search_results">
						<% @results2.each do |result| %>
						<% @num+=1 %>
						<% if @num % 10 == 0 %>
						<div class="tab-pane" id="<%=@num/10%>">
							<% end %>
							<tr>

								<td id="game_info">
									<% if signed_in? %>
									<% if in_acc_collection(result) %>
									<span class="icon-ok-sign" title="You Own This"></span>  
									<% end %>
									<% end %>


									<%= link_to result.eng_title,  result%>
								</td>

								<td id="console_info">
									<%= result.console_general.eng_name %>
								</td>

								<td id="region_info">
									<%= link_to result.region.region_title, region_path(result.region.region_id) %>
								</td>

							</tr>
							<% if @num + 2 % 10 == 0%>
						</div>
						<% end %>
						<% end %>
					</table>

					<% else %>
					<h6>Sorry, we couldn't find anything</h6>

					<%= form_tag search_index_path, class: "navbar-form navbar-left", style: "text-align: center", method: "get" do %>
					<div class="input-prepend">
						<span class="icon-search"></span>  
						<%= text_field_tag :search, params[:search],  class: "span2 search-query", placeholder: "Search for a game"%>
					</div>
					<% end %>
					<% end %>
				</div>
			</div>
		</div>

		<div class="tab-pane fade in" id="console-search-results">
			<div class="row">
				<div class="span7 offset2">

					<% @num = 0 %>
					<% if !@results3.blank? %>

					<table class="search_results">
						<% @results3.each do |result| %>
						<% @num+=1 %>
						<% if @num % 10 == 0 %>
						<div class="tab-pane" id="<%=@num/10%>">
							<% end %>
							<tr>

								<td id="game_info">
									<% if signed_in? %>
									<% if in_console_collection(result) %>
									<span class="icon-ok-sign" title="You Own This"></span>  
									<% end %>
									<% end %>


									<%= link_to result.eng_name,  result%>
								</td>

								<td id="console_info">
									<%= result.console_general.eng_name %>
								</td>

								<td id="region_info">
									<%= link_to result.region.region_title, region_path(result.region.region_id) %>
								</td>

							</tr>
							<% if @num + 2 % 10 == 0%>
						</div>
						<% end %>
						<% end %>
					</table>

					<% else %>
					<h6>Sorry, we couldn't find anything</h6>


					<%= form_tag search_index_path, class: "navbar-form navbar-left", style: "text-align: center", method: "get" do %>
					<div class="input-prepend">
						<span class="icon-search"></span>  
						<%= text_field_tag :search, params[:search],  class: "span2 search-query", placeholder: "Search for a game"%>
					</div>
					<% end %>
					<% end %>
				</div>
			</div>

		</div>

	</div>