config/routes.rb
Ooug::Application.routes.draw do
  root 'main_page#home'

  if Rails.env.production?
    get '/not_found', :to => 'errors#page_not_found'
  end

  match '/home', to: 'main_page#home', via: 'get'
  match '/help', to: 'main_page#help', via: 'get'
  match '/signUp', to: 'users#new', via: 'get'
  match '/about', to: 'main_page#about', via: 'get'
  match '/contact', to: 'main_page#contact', via: 'get'
  match '/inventory/test', to: 'inventory#test', via: 'get'
  match '/signIn',  to: 'sessions#new',         via: 'get'
  match '/signOut', to: 'sessions#destroy',     via: 'delete'

  get '/users/gruffBig' => 'users#gruffBig', as: 'gruffBig'
  get '/users/gruffSmall' => 'users#gruffSmall', as: 'gruffSmall'
  get '/users/gruffBigAcc' => 'users#gruffBigAcc', as: 'gruffBigAcc'
  get '/users/gruffSmallAcc' => 'users#gruffSmallAcc', as: 'gruffSmallAcc'
  get '/users/gruffConsole' => 'users#gruffConsole', as: 'gruffConsole'
  get '/users/gruffWish' => 'users#gruffWish', as: 'gruffWish'

  get '/wish_list/games/:id' => 'wish_list#games', as: 'wish_list_games'
  get '/wish_list/games/:id/:console_id' => 'wish_list#games', as: 'wish_list_game'

  get '/wish_list/accessories/:id' => 'wish_list#accessories', as: 'wish_list_accessories'
  get '/wish_list/accessories/:id/:console_id' => 'wish_list#accessories', as: 'wish_list_accessory'

  get '/wish_list/consoles/:id' => 'wish_list#consoles', as: 'wish_list_consoles'
  get '/wish_list/consoles/:id/:console_id' => 'wish_list#consoles', as: 'wish_list_console'
  
  get '/inventory/games/:id' => 'inventory#games', as: 'inventory_games'
  get '/inventory/games/:id/:console_id' => 'inventory#games', as: 'inventory_game'

  get '/inventory/consoles/:id' => 'inventory#consoles', as: 'inventory_consoles'
  get '/inventory/consoles/:id/:console_id' => 'inventory#consoles', as: 'inventory_console'

  get '/inventory/accessories/:id' => 'inventory#accessories', as: 'inventory_accessories'
  get '/inventory/accessories/:id/:console_id' => 'inventory#accessories', as: 'inventory_accessory'

  get '/ownership/new/:id' => 'ownership#new', as: 'new_ownership'
  get '/console_ownership/new/:id' => 'console_ownership#new', as: 'new_console_ownership'
  get '/accessories_ownership/new/:id' => 'accessories_ownership#new', as: 'new_accessories_ownership'

  get '/games_wish_list/new/:id' => 'games_wish_list#new', as: 'new_games_wish_list'
  get '/accessories_wish_list/new/:id' => 'accessories_wish_list#new', as: 'new_accessories_wish_list'  
  get '/consoles_wish_list/new/:id' => 'consoles_wish_list#new', as: 'new_consoles_wish_list'  

  resources :inventory, only: [:games, :consoles, :accessories]
  resources :users
  resources :games
  resources :wish_list
  resources :games_wish_list
  resources :accessories_wish_list
  resources :consoles_wish_list
  resources :browse_consoles
  resources :browse_accessories
  resources :consoles
  resources :accessories
  resources :console_general
  resources :console_ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :accessories_ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :region
  resources :ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :browse
  resources :search, only: [:index]
  resources :add_game, only: [:new, :create]
  resources :stats, only: [:show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :application, only: [:page_not_found]

  if Rails.env.production?
    get '*path' => redirect('/not_found')
  end
end

app/models/games_wish_list.rb
class GamesWishList < ActiveRecord::Base
	self.pluralize_table_names = false

	belongs_to :games
	belongs_to :user

	GamesWishList.joins(:user, :games)
end

app/controllers/games_wish_list_controller.rb
class GamesWishListController < ApplicationController

  before_action :signed_in_user

  before_action :correct_user,   only: [:edit, :update, :show, :destroy, :edit]

  def show
    @wish_list = GamesWishList.find_by(user_id: params[:id])
    @game = GamesWishList.find(params[:id])
  end

  def index
    @remember_token = User.hash_token(cookies[:remember_token])
    @user = User.find_by(remember_token: @remember_token)

    @wish_list = GamesWishList.find_by(user_id: current_user())
    @game = GamesWishList.joins(:user).where(:users => {:id => current_user()})

    @gameConsoles = GamesWishList.where(user_id: @user).joins(:games => :console_general).order("eng_name").uniq.pluck(:eng_name)

    if (params.has_key?(:console_id))
      @game = GamesWishList.where(user_id: current_user().id).joins(:games => :console_general).where(:console_general => {:eng_name => params[:console_id]})

    else
      @game = GamesWishList.where(:users => {:id => current_user()}).joins(:user)

    end
    
    @image = Image.all

  end

  def new
    @game = GamesWishList.new
    @overgame = Games.find(params[:id])
  end

  def edit
    @game = GamesWishList.find(params[:id])
    @overgame = GamesWishList.where(id: params[:id]).joins(:games)
  end

  def create
    @user = User.find_by(remember_token: cookies[:remember_token])

    @wishlist = GamesWishList.new(user_id: current_user().id, games_id: params[:games_wish_list][:games_id], notes: params[:games_wish_list][:notes])

    if @wishlist.save
      redirect_to @wishlist
    else

    end    
  end

  def update
    @game = GamesWishList.find(params[:id])
    if @game.update_attributes(user_id: current_user().id, games_id: params[:games_wish_list][:games_id], notes: params[:games_wish_list][:notes])
      redirect_to @game
    else
      render "edit"
    end    
  end

  def destroy
    GamesWishList.delete(params[:id])
    redirect_to wish_list_games_path(current_user)
  end

  private
  def wish_list_params
    params.require(:games_wish_list).permit(@user.id, :games_id, :notes)
  end

  def delete_params
    params.require(:ownership).permit(:id, :ean, :eng_title, :jap_title, :system, :region, :image)
  end

 # Before filters
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signIn_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(GamesWishList.find(params[:id]).user_id)
      redirect_to current_user, notice: "Sorry, you can't edit someone else's wish list"  unless current_user?(@user)
    end 


end

app/helpers/games_wish_list_helper.rb
module GamesWishListHelper

  def current_games_wish_list_ownership(id)
    @current_games_wish_list_ownership ||= GamesWishList.find_by(id: id)
  end

  def in_wish_list(game)
    @inWish = GamesWishList.find_by(user_id: current_user().id, games_id: game.id)
  end

  def wish_list_game(game)
    @user = User.find_by(remember_token: @remember_token)
    @ownership_game = GamesWishList.find_by(user_id: current_user, games_id: game)
  end

  def current_user
    remember_token = User.hash_token(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end


end

app/views/games_wish_list/edit.html.erb
<% provide(:title, "Edit " + @overgame.first.games.eng_title) %>
<%= render 'shared/game_error_messages' %> 

<div class="container inventory_games" style="background-color: white; padding-top: 60px;">
<h1 class="game_title"><%= @overgame.first.games.eng_title %></h1>

<div class="row span10" style="margin-top: 100px">
  <div class="">

    <%= form_for(@game, :html => {:class => "form-horizontal"}) do |f| %>

	<%= f.label :notes, class: "col-sm-2 control-label", style: "padding-right: 5px"%>
	<%= f.text_area(:notes, cols: 500, rows: 3) %>

	<%= f.text_field :games_id, value: @overgame.first.games.id,  class: "readonly" , style: "visibility: hidden"%>
<br />
      <%= f.submit "Update Wish Info", class: "btn btn-inverse btn-small" %>
    <% end %>
</div>

</div>
</div>

app/views/games_wish_list/index.html.erb
<%= render 'layouts/gamesWishListSideBar' %>

<% 
    if (params.has_key?(:console_id))
        provide(:title, 'All your ' + params[:console_id] + ' games')
    else
        provide(:title, 'All Games In Your Collection')
    end
%>
<div class="container inventory_games" style="background-color: white; padding-top: 60px;">
<table class="game_table_info">
<% @game.each do |game| %>
    <tr height="50px">
        <td id="game_info">
          <%= link_to game.games.eng_title, games_wish_list_path(game.id) %>

        </td>

        <td id="console_info">
          <%= link_to game.games.console_general.eng_name, console_general_path(game.games.console_general.id) %>
        </td>

        <td id="region_info">
          <%= link_to game.games.region.region_title, region_path(game.games.region.region_id) %>
        </td>
    </tr>
<% end %>

</table>
</div>

app/views/games_wish_list/new.html.erb
<% provide(:title, "Add " + @overgame.eng_title + " To Your Wish List") %>
<%= #render 'shared/game_error_messages' 
%> 
<div class="container inventory_games" style="background-color: white; padding-top: 60px;">
<h1 class="game_title"><%= @overgame.eng_title %></h1>
<h5 class="game_title"><%= (@overgame.jap_title ? @overgame.jap_title : "" );%></h5>

<div class="row offset2">
    <%= form_for(@game, url: {action: "create"}) do |f| %>
	<%= f.label :notes, class: "col-sm-2 control-label", style: "padding-right: 5px"%>
	<%= f.text_area(:notes, cols: 500, rows: 3) %>

	<%= f.text_field :games_id, value: @overgame.id,  class: "readonly" , style: "visibility: hidden"%>
<br />
      <%= f.submit "Add To Wish List", class: "btn btn-inverse btn-small" %>
    <% end %>
</div>

</div>

app/views/games_wish_list/show.html.erb
<div class="container inventory_games" style="background-color: white; padding-top: 60px;">
<h1 class="game_title"><%= @game.games.eng_title %></h1>
<h5 class="game_title"><%= @game.games.jap_title %></h5>
<h5 class="game_title"><%= @game.games.region.region_title %></h5>

<p><%= @game.notes %></p>

<%= link_to "Edit Game", edit_games_wish_list_path(current_games_wish_list_ownership(params[:id])), class: "btn btn-inverse btn-small offset2 span2" %>
<%= link_to "Remove From Wish List", @game, :confirm => 'Remove from wish list?' , class: "btn btn-inverse btn-small span2", method: "delete" 
%>
</div>