config/routes.rb
Ooug::Application.routes.draw do
  root 'main_page#home'

  if Rails.env.production?
    get '/not_found', :to => 'errors#page_not_found'
  end

  match '/home', to: 'main_page#home', via: 'get'
  match '/help', to: 'main_page#help', via: 'get'
  match '/signUp', to: 'users#new', via: 'get'
  match '/about', to: 'main_page#about', via: 'get'
  match '/contact', to: 'main_page#contact', via: 'get'
  match '/inventory/test', to: 'inventory#test', via: 'get'
  match '/signIn',  to: 'sessions#new',         via: 'get'
  match '/signOut', to: 'sessions#destroy',     via: 'delete'

  get '/users/gruffBig' => 'users#gruffBig', as: 'gruffBig'
  get '/users/gruffSmall' => 'users#gruffSmall', as: 'gruffSmall'
  get '/users/gruffBigAcc' => 'users#gruffBigAcc', as: 'gruffBigAcc'
  get '/users/gruffSmallAcc' => 'users#gruffSmallAcc', as: 'gruffSmallAcc'
  get '/users/gruffConsole' => 'users#gruffConsole', as: 'gruffConsole'
  get '/users/gruffWish' => 'users#gruffWish', as: 'gruffWish'

  get '/wish_list/games/:id' => 'wish_list#games', as: 'wish_list_games'
  get '/wish_list/games/:id/:console_id' => 'wish_list#games', as: 'wish_list_game'

  get '/wish_list/accessories/:id' => 'wish_list#accessories', as: 'wish_list_accessories'
  get '/wish_list/accessories/:id/:console_id' => 'wish_list#accessories', as: 'wish_list_accessory'

  get '/wish_list/consoles/:id' => 'wish_list#consoles', as: 'wish_list_consoles'
  get '/wish_list/consoles/:id/:console_id' => 'wish_list#consoles', as: 'wish_list_console'
  
  get '/inventory/games/:id' => 'inventory#games', as: 'inventory_games'
  get '/inventory/games/:id/:console_id' => 'inventory#games', as: 'inventory_game'

  get '/inventory/consoles/:id' => 'inventory#consoles', as: 'inventory_consoles'
  get '/inventory/consoles/:id/:console_id' => 'inventory#consoles', as: 'inventory_console'

  get '/inventory/accessories/:id' => 'inventory#accessories', as: 'inventory_accessories'
  get '/inventory/accessories/:id/:console_id' => 'inventory#accessories', as: 'inventory_accessory'

  get '/ownership/new/:id' => 'ownership#new', as: 'new_ownership'
  get '/console_ownership/new/:id' => 'console_ownership#new', as: 'new_console_ownership'
  get '/accessories_ownership/new/:id' => 'accessories_ownership#new', as: 'new_accessories_ownership'

  get '/games_wish_list/new/:id' => 'games_wish_list#new', as: 'new_games_wish_list'
  get '/accessories_wish_list/new/:id' => 'accessories_wish_list#new', as: 'new_accessories_wish_list'  
  get '/consoles_wish_list/new/:id' => 'consoles_wish_list#new', as: 'new_consoles_wish_list'  

  resources :inventory, only: [:games, :consoles, :accessories]
  resources :users
  resources :games
  resources :wish_list
  resources :games_wish_list
  resources :accessories_wish_list
  resources :consoles_wish_list
  resources :browse_consoles
  resources :browse_accessories
  resources :consoles
  resources :accessories
  resources :console_general
  resources :console_ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :accessories_ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :region
  resources :ownership, only: [:show, :update, :edit, :create, :destroy, :new]
  resources :browse
  resources :search, only: [:index]
  resources :add_game, only: [:new, :create]
  resources :stats, only: [:show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :application, only: [:page_not_found]

  if Rails.env.production?
    get '*path' => redirect('/not_found')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :alias,  presence: true, length: { maximum: 50 },
  uniqueness: { case_sensitive: false }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 8 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

   def User.hash_token(token)
     Digest::SHA1.hexdigest(token.to_s)
  end

  has_many :ownership
  has_many :games, through: :ownerships

  private

  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end
end

app/models/users.rb
class Users < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :alias,  presence: true, length: { maximum: 50 },
  uniqueness: { case_sensitive: false }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 8 }

  has_many :ownership
  has_many :games, through: :ownerships

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:edit, :show, :update]

  before_action :correct_user,   only: [:edit, :update, :show]

  def gruffConsole
    @remember_token = User.hash_token(cookies[:remember_token])
    @user = User.find_by(remember_token: @remember_token)
    @consoleNames = ConsoleOwnership.where(user_id: @user).joins(:consoles => :console_general).uniq.pluck("console_general.eng_name")
    @consoleCount = ConsoleOwnership.where(user_id: @user).joins(:consoles => :console_general).count
    (@consoleCount >= 20 ? '' : @consoleCount = 20)

    g = Gruff::Spider.new((@consoleCount/10).floor)

    g.top_margin = 50
    g.bottom_margin = 75

    @ownership = ConsoleOwnership.where(user_id: @user).joins(:consoles => :console_general)

    @consoleNames.each do |console|
      g.data console, ConsoleOwnership.where(user_id: @user).joins(:consoles => :console_general).where(:console_general => {:eng_name => console}).count
    end

    g.theme = Gruff::Themes::PASTEL
    # g.legend_font_size = 12
    
    send_data(g.to_blob, :filename => "pie.png", :type => 'image/png', :disposition=> 'inline')
  end

  def gruffWish
    @remember_token = User.hash_token(cookies[:remember_token])
    @user = User.find_by(remember_token: @remember_token)
    @consoleNames = GamesWishList.where(user_id: @user).joins(:games => :console_general).uniq.pluck(:eng_name)
    @wishCount = GamesWishList.where(user_id: @user).joins(:games => :console_general).count
    (@wishCount >= 20 ? '' : @wishCount = 20)
    
    
    g = Gruff::Spider.new((@wishCount/10).floor)

    g.top_margin = 50
    g.bottom_margin = 75

    @ownership = GamesWishList.where(user_id: @user).joins(:games => :console_general)

    @consoleNames.each do |console|
      g.data console, ConsoleOwnership.where(user_id: @user).joins(:consoles => :console_general).where(:console_general => {:eng_name => console}).count
    end

    g.theme = Gruff::Themes::PASTEL
    # g.legend_font_size = 12
    
    send_data(g.to_blob, :filename => "pie.png", :type => 'image/png', :disposition=> 'inline')
  end

  def gruffBig
    @remember_token = User.hash_token(cookies[:remember_token])
    @user = User.find_by(remember_token: @remember_token)
    @consoleNames = Ownership.where(user_id: @user).joins(:games => :console_general).uniq.pluck(:eng_name)
    @gamesCount = Ownership.where(user_id: @user).joins(:games => :console_general).count
    (@gamesCount >= 20 ? '' : @gamesCount = 20)

    g = Gruff::Spider.new((@gamesCount/10).floor)

    g.top_margin = 50
    g.bottom_margin = 75
    #g.legend_font_size = 15 #maybe make this dependant on the size liuke the width in the initializer

    @ownership = Ownership.where(user_id: @user).joins(:games => :console_general)

    @consoleNames.each do |console|
      g.data console, Ownership.where(user_id: @user).joins(:games => :console_general).where(:console_general => {:eng_name => console}).count
    end

    g.theme = Gruff::Themes::PASTEL
    
    send_data(g.to_blob, :filename => "pie.png", :type => 'image/png', :disposition=> 'inline')
  end

  def gruffBigAcc
    @remember_token = User.hash_token(cookies[:remember_token])
    @user = User.find_by(remember_token: @remember_token)
    @consoleNames = AccessoriesOwnership.where(user_id: @user).joins(:accessories => :console_general).uniq.pluck(:eng_name)
    @accCount = AccessoriesOwnership.where(user_id: @user).joins(:accessories => :console_general).count
    (@accCount >= 20 ? '' : @accCount = 20)
    
    g = Gruff::Spider.new((@accCount/10).floor)

    g.top_margin = 50
    g.bottom_margin = 75

    @ownership = AccessoriesOwnership.where(user_id: @user).joins(:accessories => :console_general)

    @consoleNames.each do |console|
      g.data console, AccessoriesOwnership.where(user_id: @user).joins(:accessories => :console_general).where(:console_general => {:eng_name => console}).count
    end

    g.theme = Gruff::Themes::PASTEL
    # g.legend_font_size = 12
    
    send_data(g.to_blob, :filename => "pie.png", :type => 'image/png', :disposition=> 'inline')
  end

  def show
    @user = User.find(params[:id])
    @game_count = Ownership.where(user_id: @user.id).all.count
    @console_count = ConsoleOwnership.where(user_id: @user.id).all.count
    @accessory_count = AccessoriesOwnership.where(user_id: @user.id).all.count
    
  end

  def new
    @user = User.new
  end

  def signIn
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to OOUG!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

private 

  def user_params
    params.require(:user).permit(:alias, :email, :password, :password_confirmation)
  end

# Before filters
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signIn_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to current_user, notice: "There is no " + current_user.alias + " only Zool.\nBut seriously, you can only look at your info, not someone else's"  unless current_user?(@user)
    end 
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.alias, class: "gravatar")
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit " + @user.alias) %>
<h1>Change Your Settings</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :alias %>
      <%= f.text_field :alias %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="span4 offset2">

<h1 class="centered-header">Sign up</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :alias, class: "col-sm-2 control-label", style: "padding-right: 5px" %>
      <%= f.text_field :alias, placeholder: "you will be known by this name"%>

      <%= f.label :email, class: "col-sm-2 control-label", style: "padding-right: 5px" %>
      <%= f.text_field :email, placeholder: "name@domain.tld" %>

      <%= f.label :password, class: "col-sm-2 control-label", style: "padding-right: 5px" %>
      <%= f.password_field :password, placeholder: "min of 8 characters please"%>

      <%= f.label :password_confirmation, "Confirm Password", class: "col-sm-2 control-label", style: "padding-right: 5px"%>
      <%= f.password_field :password_confirmation, placeholder: "same as above" %>

      <%= f.submit "Create my account", class: "btn btn-primary btn-sm" %>
    <% end %>
</div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.alias + "'s profile") %>

<h1 style="text-align: center">
	<%= gravatar_for @user %>
	<%= @user.alias %>
</h1>

<p id="game_info">
	Number of games in your collection: <%= link_to @game_count, inventory_games_path(current_user) %> <br />
	number of consoles in your collection: <%= link_to @console_count, inventory_consoles_path(current_user) %> <br />
	Number of accessories in your collection: <%= link_to @accessory_count, inventory_accessories_path(current_user) %> <br />
</p>

<!-- Fix this later too, imagemagick and ghostscript aren't playing nice -->
<ul class="nav nav-tabs" id="game_count_tabs">
	<li class="active"><a href="#above10" data-toggle="tab">Game Chart</a></li>
	<li><a href="#accabove10" data-toggle="tab"> Accessory Chart</a></li>
	<li><a href="#consoles" data-toggle="tab"> Console Chart </a></li>
	<li><a href="#wish" data-toggle="tab"> Wish List Chart </a></li>
</ul>

<div class="tab-content">

	<div class="tab-pane active" id="above10">
		<div class="row">
			<div class="span7 offset2">

				<%= image_tag(url_for(:controller => 'users', :action => 'gruffBig'), alt: "Spider Chart of Your Largest Collection") %>



			</div>
		</div>
	</div>

	<div class="tab-pane fade in" id="accabove10">
		<div class="row">
			<div class="span7 offset2">

				<%= image_tag(url_for(:controller => 'users', :action => 'gruffBigAcc'), alt: "Spider Chart of Your Largest Accessory Collection") %>



			</div>
		</div>
	</div>

	<div class="tab-pane fade in" id="consoles">
	  <div class="row">
	    <div class="span7 offset2">
	      
	      <%= image_tag(url_for(:controller => 'users', :action => 'gruffConsole'), alt: "Spider Chart of your consoles") %>
	      
	    </div>
	  </div>
	</div>    
	
	<div class="tab-pane fade in" id="wish">
	  <div class="row">
	    <div class="span7 offset2">
	      
	      <%= image_tag(url_for(:controller => 'users', :action => 'gruffWish'), alt: "Spider Chart of your wish list") %>
	      
	    </div>
	  </div>
	</div>    
	
</div>

app/views/users/signIn.html.erb
<div class="row">
  <div class="span4 offset2">

<h1 class="centered-header">Sign In</h1>

    <%= form_for(@user) do |f| %>

      <%= f.label :email, class: "col-sm-2 control-label", style: "padding-right: 5px"%>
      <%= f.text_field :email, placeholder: "name@domain.tld"%>

      <%= f.label :password, class: "col-sm-2 control-label", style: "padding-right: 5px"%>
      <%= f.password_field :password%>
      <br />
      <%= f.submit "Sign In", class: "btn btn-primary btn-sm" %>
    <% end %>

</div>
</div>